# Generated by Django 2.1.5 on 2020-05-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub', models.CharField(max_length=64)),
                ('topping_one', models.CharField(max_length=64)),
                ('topping_two', models.CharField(max_length=64)),
                ('topping_three', models.CharField(max_length=64)),
                ('special', models.CharField(max_length=64)),
            ],
        ),
    ]
