# Generated by Django 2.1.5 on 2020-05-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='special',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='topping_one',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='topping_three',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='topping_two',
        ),
        migrations.AddField(
            model_name='pizza',
            name='large',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pizza',
            name='small',
            field=models.FloatField(default=0),
        ),
    ]
