# Generated by Django 2.1.5 on 2020-05-14 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_subs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subs',
            new_name='Sub',
        ),
    ]
