# Generated by Django 2.1.5 on 2020-05-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200514_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regular_pizza',
            name='item',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='sicilian_pizza',
            name='item',
            field=models.CharField(max_length=64),
        ),
    ]
