# Generated by Django 2.1.5 on 2020-05-14 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200514_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pasta',
            old_name='name',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='salad',
            old_name='name',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='topping',
            old_name='name',
            new_name='item',
        ),
    ]
