# Generated by Django 2.1.5 on 2020-05-14 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200514_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pasta',
            old_name='item',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='salad',
            old_name='item',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='topping',
            old_name='item',
            new_name='name',
        ),
    ]
